/*TOTAL DE AUDIOS CORRIGIDOS*/
DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
SELECT DISTINCT NU_SEQUENCIAL, CD_ITEM, TP_STATUS
into pmcq..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
FROM REPOSITORIO_MTD..ARQ_SO_077_D_1612_20240709104707_000141217 
WHERE TP_STATUS = '99'
  AND TRY_CONVERT(DATE, DT_LANCAMENTO, 103) > '2024-06-01'

/*TOTAL DE AUDIOS ENVIADOS PARA CORREÇÃO*/
DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_077_MEXICO_ENVIADOS
SELECT DISTINCT NU_SEQUENCIAL, CD_ITEM
INTO PMCQ..TEMP_ARTHUR_077_MEXICO_ENVIADOS
FROM REPOSITORIO_MTD..ARQ_SO_077_D_1612_20240709104707_000141217 
WHERE 
   TRY_CONVERT(DATE, DT_LANCAMENTO, 103) > '2024-06-01'

/*QTDE DE AUDIOS SINCRONIZADOS*/
DROP TABLE IF EXISTS #008_FILTRADO
SELECT CD_REGISTRO_CAED, VL_CAMPO_005, VL_CAMPO_009, VL_CAMPO_013 
INTO #008_FILTRADO
FROM [REPOSITORIO_MTD].[DBO].ARQ_DA_008_D_1612_20240709092029_000022172 
WHERE CD_REGISTRO_CAED IN(
	SELECT NU_SEQUENCIAL FROM REPOSITORIO_MTD..ARQ_SO_077_D_1612_20240709104707_000141217  
	WHERE TRY_CONVERT(DATE, DT_LANCAMENTO, 103) > '2024-06-01'
)

/*----------------------------*/
DROP TABLE IF EXISTS #008_PALAPSEUDOTEXTO
SELECT 'PALAVRA' AS TIPO,VL_CAMPO_005, CD_REGISTRO_CAED
INTO #008_PALAPSEUDOTEXTO
FROM #008_FILTRADO
WHERE CD_REGISTRO_CAED NOT LIKE '%-%'
  AND VL_CAMPO_005 IS NOT NULL
UNION
SELECT 'PSEUDOPALAVRA' AS TIPO, VL_CAMPO_009, CD_REGISTRO_CAED
FROM #008_FILTRADO
WHERE CD_REGISTRO_CAED NOT LIKE '%-%'
  AND VL_CAMPO_009 IS NOT NULL
UNION
SELECT 'TEXTO' AS TIPO, VL_CAMPO_013, CD_REGISTRO_CAED
FROM #008_FILTRADO
WHERE CD_REGISTRO_CAED NOT LIKE '%-%'
  AND VL_CAMPO_013 IS NOT NULL

/*----------------------------*/
DROP TABLE IF EXISTS #UM
DROP TABLE IF EXISTS #DOIS
DROP TABLE IF EXISTS #TRES
SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_CORRIGIDOS -- CORRIGIDOS
	INTO #UM
FROM REPOSITORIO_MTD..TB_005_AUTORIZADOS_09072024 A
JOIN pmcq..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
WHERE S.TP_STATUS = '99'
GROUP BY A.NM_ESTADO,A.CD_ESTADO

SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_ENVIADOS -- ENVIADOS
	INTO #DOIS
FROM REPOSITORIO_MTD..TB_005_AUTORIZADOS_09072024 A
JOIN pmcq..TEMP_ARTHUR_077_MEXICO_ENVIADOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
GROUP BY A.NM_ESTADO,A.CD_ESTADO
ORDER BY NM_ESTADO ASC

SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_SINCRONIZADOS -- SINCRONIZADOS
	INTO #TRES
FROM REPOSITORIO_MTD..TB_005_AUTORIZADOS_09072024 A
JOIN #008_PALAPSEUDOTEXTO S 
    ON A.NU_SEQUENCIAL = S.CD_REGISTRO_CAED
GROUP BY A.NM_ESTADO,A.CD_ESTADO
ORDER BY NM_ESTADO ASC;
/*------------FIM-------------*/


/*-------------------------------------------------------------------------------------- RELATORIO POR ESTADO */
SELECT A.NM_ESTADO, 
	   C.TOTAL_AUDIOS_SINCRONIZADOS, 
	   B.TOTAL_AUDIOS_ENVIADOS, 
	   A.TOTAL_AUDIOS_CORRIGIDOS  
FROM #UM A
JOIN #DOIS B ON A.CD_ESTADO = B.CD_ESTADO 
JOIN #TRES C ON B.CD_ESTADO = C.CD_ESTADO
ORDER BY A.NM_ESTADO ASC






