/*PEGA A TABELA MAIS NOVA E COLOCA EM UMA TABELA TEMPORARIA, PARA SER USADA ABAIXO*/
DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_CORRETORES_185 -- 185
SELECT * 
INTO PMCQ..TEMP_ARTHUR_CORRETORES_185
FROM [T6_MEXICO_FLUENCIA_2024]..[ARQ_US_185_D_1612_20240709092522_000003899]

DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_GERAL_008 -- 008
SELECT * 
INTO PMCQ..TEMP_ARTHUR_GERAL_008
FROM REPOSITORIO_MTD..ARQ_DA_008_D_1612_20240716092037_000035453    

DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_GERAL_005 -- 005
SELECT * 
INTO PMCQ..TEMP_ARTHUR_GERAL_005
FROM REPOSITORIO_MTD.dbo.TB_005_AUTORIZADOS_16072024

DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_GERAL_077 -- 077
SELECT * 
INTO PMCQ..TEMP_ARTHUR_GERAL_077
FROM REPOSITORIO_MTD.. ARQ_SO_077_D_1612_20240716092322_000032494  	   
WHERE NU_SEQUENCIAL IN(
	SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
)

/*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/
/*||||||||||||||||||||||||||||||||||||INICIO |||||||||||||||||||||||||||||||||||*/
/*||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||*/

/*||||||||||||||||||||||||||TOTAL DE AUDIOS CORRIGIDOS||||||||||||||||||||||||||*/
PRINT 'INICIO TOTAL DE AUDIOS CORRIGIDOS'
DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_077_MEXICO_CORR
SELECT NU_SEQUENCIAL, CD_ITEM, MAX(NU_CORRECAO) AS MAIOR_CORRECAO
INTO PMCQ..TEMP_ARTHUR_077_MEXICO_CORR
FROM PMCQ..TEMP_ARTHUR_GERAL_077 
WHERE NU_SEQUENCIAL IN(
	SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
) AND TP_STATUS = '99'
GROUP BY NU_SEQUENCIAL, CD_ITEM

DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
SELECT B.*
INTO PMCQ..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
 FROM PMCQ..TEMP_ARTHUR_077_MEXICO_CORR A
INNER JOIN PMCQ..TEMP_ARTHUR_GERAL_077 B 
	ON A.NU_SEQUENCIAL = B.NU_SEQUENCIAL
	AND A.CD_ITEM = B.CD_ITEM
	AND A.MAIOR_CORRECAO = B.NU_CORRECAO 


/*TOTAL DE AUDIOS ENVIADOS PARA CORREÇÃO*/
DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_077_MEXICO_ENV
SELECT NU_SEQUENCIAL, CD_ITEM, MAX(NU_CORRECAO) AS MAIOR_CORRECAO
INTO PMCQ..TEMP_ARTHUR_077_MEXICO_ENV
FROM PMCQ..TEMP_ARTHUR_GERAL_077 
WHERE NU_SEQUENCIAL IN(
	SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
)
GROUP BY NU_SEQUENCIAL, CD_ITEM

DROP TABLE IF EXISTS pmcq..TEMP_ARTHUR_077_MEXICO_ENVIADOS
SELECT B.*
INTO PMCQ..TEMP_ARTHUR_077_MEXICO_ENVIADOS 
 FROM PMCQ..TEMP_ARTHUR_077_MEXICO_ENV A
INNER JOIN PMCQ..TEMP_ARTHUR_GERAL_077 B 
	ON A.NU_SEQUENCIAL = B.NU_SEQUENCIAL
	AND A.CD_ITEM = B.CD_ITEM
	AND A.MAIOR_CORRECAO = B.NU_CORRECAO 

/*QTDE DE AUDIOS SINCRONIZADOS*/
DROP TABLE IF EXISTS PMCQ..temp_MEXICO_008SEQUE
SELECT NU_SEQUENCIAL, CD_REGISTRO_CAED, VL_CAMPO_005, VL_CAMPO_009, VL_CAMPO_013 
INTO PMCQ..temp_MEXICO_008SEQUE
FROM PMCQ..TEMP_ARTHUR_GERAL_008
WHERE CD_REGISTRO_CAED IN(
	SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
)
PRINT 'FIM TOTAL DE AUDIOS CORRIGIDOS'
/*------------------------------------------*/
/*---------------SINCRONIZADOS-------------*/
PRINT 'INICIO SINCRONIZADOS'
DROP TABLE IF EXISTS TEMP_ARTHUR_008_PPT
SELECT 'PALAVRA' AS TIPO,VL_CAMPO_005, CD_REGISTRO_CAED
INTO TEMP_ARTHUR_008_PPT
FROM pmcq..TEMP_ARTHUR_008_MEXICO_SINCRONIZADO
WHERE CD_REGISTRO_CAED NOT LIKE '%-%'
  AND VL_CAMPO_005 IS NOT NULL
UNION
SELECT 'PSEUDOPALAVRA' AS TIPO, VL_CAMPO_009, CD_REGISTRO_CAED
FROM pmcq..TEMP_ARTHUR_008_MEXICO_SINCRONIZADO
WHERE CD_REGISTRO_CAED NOT LIKE '%-%'
  AND VL_CAMPO_009 IS NOT NULL
UNION
SELECT 'TEXTO' AS TIPO, VL_CAMPO_013, CD_REGISTRO_CAED
FROM pmcq..TEMP_ARTHUR_008_MEXICO_SINCRONIZADO
WHERE CD_REGISTRO_CAED NOT LIKE '%-%'
  AND VL_CAMPO_013 IS NOT NULL
PRINT 'FIM SINCRONIZADOS'
/*------------------------------------------*/
/*------------------ENVIADOS----------------*/
PRINT 'INICIO ENVIADOS'
DROP TABLE IF EXISTS TEMP_ARTHUR_077_PPT_ENVIADOS
SELECT 'PALAVRA' AS TIPO, NU_SEQUENCIAL, CD_ITEM, TP_STATUS
INTO TEMP_ARTHUR_077_PPT_ENVIADOS
FROM PMCQ..TEMP_ARTHUR_077_MEXICO_ENVIADOS
WHERE CD_ITEM IN (
						SELECT CD_CAMPO_001
						FROM T6_MEXICO_FLUENCIA_2024..[ARQ_IN_011_D_1612_20240625160906_000000008] 
						WHERE CD_AVALIACAO = '18961801'
					)

UNION
SELECT 'PSEUDOPALAVRA' AS TIPO, NU_SEQUENCIAL, CD_ITEM, TP_STATUS
FROM PMCQ..TEMP_ARTHUR_077_MEXICO_ENVIADOS
WHERE CD_ITEM IN (
						SELECT CD_CAMPO_002
						FROM T6_MEXICO_FLUENCIA_2024..[ARQ_IN_011_D_1612_20240625160906_000000008] 
						WHERE CD_AVALIACAO = '18961801'
					)

UNION
SELECT 'TEXTO' AS TIPO, NU_SEQUENCIAL, CD_ITEM, TP_STATUS
FROM PMCQ..TEMP_ARTHUR_077_MEXICO_ENVIADOS
WHERE CD_ITEM IN (
						SELECT CD_CAMPO_003
						FROM T6_MEXICO_FLUENCIA_2024..[ARQ_IN_011_D_1612_20240625160906_000000008] 
						WHERE CD_AVALIACAO = '18961801'
					)
PRINT 'FIM ENVIADOS'
/*-----------------------------------------------*/
/*-------------------CORRIGIDOS------------------*/
PRINT 'INICIO CORRIGIDOS'
DROP TABLE IF EXISTS TEMP_ARTHUR_077_PPT_CORRIGIDOS
SELECT 'PALAVRA' AS TIPO, NU_SEQUENCIAL, CD_ITEM , TP_STATUS
INTO TEMP_ARTHUR_077_PPT_CORRIGIDOS
FROM PMCQ..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
WHERE CD_ITEM IN (
						SELECT CD_CAMPO_001
						FROM T6_MEXICO_FLUENCIA_2024..[ARQ_IN_011_D_1612_20240625160906_000000008] 
						WHERE CD_AVALIACAO = '18961801'
					)

UNION
SELECT 'PSEUDOPALAVRA' AS TIPO, NU_SEQUENCIAL, CD_ITEM, TP_STATUS
FROM PMCQ..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
WHERE CD_ITEM IN (
						SELECT CD_CAMPO_002
						FROM T6_MEXICO_FLUENCIA_2024..[ARQ_IN_011_D_1612_20240625160906_000000008] 
						WHERE CD_AVALIACAO = '18961801'
					)

UNION
SELECT 'TEXTO' AS TIPO, NU_SEQUENCIAL, CD_ITEM, TP_STATUS
FROM PMCQ..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS
WHERE CD_ITEM IN (
						SELECT CD_CAMPO_003
						FROM T6_MEXICO_FLUENCIA_2024..[ARQ_IN_011_D_1612_20240625160906_000000008] 
						WHERE CD_AVALIACAO = '18961801'
					)
PRINT 'FIM CORRIGIDOS'
/*----------------------------*/
/*---------- ESTADO ----------*/
DROP TABLE IF EXISTS #CORRIGIDOS_ESTADO
DROP TABLE IF EXISTS #ENVIADOS_ESTADO
DROP TABLE IF EXISTS #SINCRONIZADOS_ESTADO
SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_CORRIGIDOS -- CORRIGIDOS POR ESTADO
	INTO #CORRIGIDOS_ESTADO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN pmcq..TEMP_ARTHUR_077_MEXICO_CORRIGIDOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
WHERE S.TP_STATUS = '99'
GROUP BY A.NM_ESTADO,A.CD_ESTADO

SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_ENVIADOS -- ENVIADOS POR ESTADO
	INTO #ENVIADOS_ESTADO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN pmcq..TEMP_ARTHUR_077_MEXICO_ENVIADOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
GROUP BY A.NM_ESTADO,A.CD_ESTADO
ORDER BY NM_ESTADO ASC

SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_SINCRONIZADOS -- SINCRONIZADOS POR ESTADO
	INTO #SINCRONIZADOS_ESTADO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN TEMP_ARTHUR_008_PPT S 
    ON A.NU_SEQUENCIAL = S.CD_REGISTRO_CAED
GROUP BY A.NM_ESTADO,A.CD_ESTADO
ORDER BY NM_ESTADO ASC;
/*------------FIM-------------*/

/*---------------------------------------------*/
/*---------- ESTADO E TIPO DE ESCOLA ----------*/
DROP TABLE IF EXISTS #CORRIGIDOS_ESTADO_TIPO
DROP TABLE IF EXISTS #ENVIADOS_ESTADO_TIPO
DROP TABLE IF EXISTS #SINCRONIZADOS_ESTADO_TIPO
SELECT 
    A.NM_ESTADO,
	A.DC_DEP_ADMINISTRATIVA,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_CORRIGIDOS -- CORRIGIDOS POR ESTADO E TIPO DE ESCOLA
	INTO #CORRIGIDOS_ESTADO_TIPO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN PMCQ..TEMP_ARTHUR_077_PPT_CORRIGIDOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
WHERE S.TP_STATUS = '99'
GROUP BY A.NM_ESTADO,A.CD_ESTADO,A.DC_DEP_ADMINISTRATIVA


SELECT 
    A.NM_ESTADO,
	A.DC_DEP_ADMINISTRATIVA,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_ENVIADOS -- ENVIADOS POR ESTADO E TIPO DE ESCOLA
	INTO #ENVIADOS_ESTADO_TIPO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN pmcq..TEMP_ARTHUR_077_MEXICO_ENVIADOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
GROUP BY A.NM_ESTADO,A.CD_ESTADO,A.DC_DEP_ADMINISTRATIVA
ORDER BY NM_ESTADO ASC

SELECT 
    A.NM_ESTADO,
	A.DC_DEP_ADMINISTRATIVA,
	A.CD_ESTADO,
    COUNT(*) AS TOTAL_AUDIOS_SINCRONIZADOS -- SINCRONIZADOS POR ESTADO E TIPO DE ESCOLA
	INTO #SINCRONIZADOS_ESTADO_TIPO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN TEMP_ARTHUR_008_PPT S 
    ON A.NU_SEQUENCIAL = S.CD_REGISTRO_CAED
GROUP BY A.NM_ESTADO,A.CD_ESTADO,A.DC_DEP_ADMINISTRATIVA
ORDER BY NM_ESTADO ASC;
/*------------FIM-------------*/

/*---------------------------------------------*/
/*---------- ESTADO E TIPO DE AUDIO ----------*/
DROP TABLE IF EXISTS #CORRIGIDOS_ESTADO_TIPO_AUDIO
DROP TABLE IF EXISTS #ENVIADOS_ESTADO_TIPO_AUDIO
DROP TABLE IF EXISTS #SINCRONIZADOS_ESTADO_TIPO_AUDIO
SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
	S.TIPO,
    COUNT(*) AS TOTAL_AUDIOS_CORRIGIDOS -- CORRIGIDOS POR ESTADO E TIPO DE ESCOLA
	INTO #CORRIGIDOS_ESTADO_TIPO_AUDIO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN pmcq..TEMP_ARTHUR_077_PPT_CORRIGIDOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
WHERE S.TP_STATUS = '99'
GROUP BY A.NM_ESTADO,A.CD_ESTADO,S.TIPO


SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
	S.TIPO,
    COUNT(*) AS TOTAL_AUDIOS_ENVIADOS -- ENVIADOS POR ESTADO E TIPO DE ESCOLA
	INTO #ENVIADOS_ESTADO_TIPO_AUDIO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN TEMP_ARTHUR_077_PPT_ENVIADOS S 
    ON A.NU_SEQUENCIAL = S.NU_SEQUENCIAL
GROUP BY A.NM_ESTADO,A.CD_ESTADO,S.TIPO
ORDER BY NM_ESTADO ASC

SELECT 
    A.NM_ESTADO,
	A.CD_ESTADO,
	S.TIPO,
    COUNT(*) AS TOTAL_AUDIOS_SINCRONIZADOS -- SINCRONIZADOS POR ESTADO E TIPO DE ESCOLA
	INTO #SINCRONIZADOS_ESTADO_TIPO_AUDIO
FROM PMCQ..TEMP_ARTHUR_GERAL_005 A
JOIN TEMP_ARTHUR_008_PPT S 
    ON A.NU_SEQUENCIAL = S.CD_REGISTRO_CAED
GROUP BY A.NM_ESTADO,A.CD_ESTADO,S.TIPO
ORDER BY NM_ESTADO ASC;


/*------------------------------------------------------------------------------------------------------------*/
/*-------------------------------------------------- RELATORIO -----------------------------------------------*/
/*------------------------------------------------------------------------------------------------------------*/

/*-------------------------------------------------------------------------------------- RELATORIO POR ESTADO */
SELECT A.NM_ESTADO, 
	   C.TOTAL_AUDIOS_SINCRONIZADOS, 
	   B.TOTAL_AUDIOS_ENVIADOS, 
	   A.TOTAL_AUDIOS_CORRIGIDOS  
FROM #CORRIGIDOS_ESTADO A
JOIN #ENVIADOS_ESTADO B ON A.CD_ESTADO = B.CD_ESTADO 
JOIN #SINCRONIZADOS_ESTADO C ON B.CD_ESTADO = C.CD_ESTADO
ORDER BY A.NM_ESTADO ASC

/*-------------------------------------------------------------------------------------- ESTADO E TIPO DE ESCOLA */
SELECT A.NM_ESTADO, 
		A.DC_DEP_ADMINISTRATIVA,
	   C.TOTAL_AUDIOS_SINCRONIZADOS, 
	   B.TOTAL_AUDIOS_ENVIADOS, 
	   A.TOTAL_AUDIOS_CORRIGIDOS 
FROM #CORRIGIDOS_ESTADO_TIPO A
JOIN #ENVIADOS_ESTADO_TIPO B ON A.CD_ESTADO = B.CD_ESTADO AND A.DC_DEP_ADMINISTRATIVA = B.DC_DEP_ADMINISTRATIVA
JOIN #SINCRONIZADOS_ESTADO_TIPO C ON B.CD_ESTADO = C.CD_ESTADO AND B.DC_DEP_ADMINISTRATIVA = C.DC_DEP_ADMINISTRATIVA
ORDER BY A.NM_ESTADO ASC

/*-------------------------------------------------------------------------------------- ESTADO E TIPO DE AUDIO */
SELECT A.NM_ESTADO, 
	   B.TIPO,
	   C.TOTAL_AUDIOS_SINCRONIZADOS, 
	   B.TOTAL_AUDIOS_ENVIADOS, 
	   A.TOTAL_AUDIOS_CORRIGIDOS 
FROM #CORRIGIDOS_ESTADO_TIPO_AUDIO A
JOIN #ENVIADOS_ESTADO_TIPO_AUDIO B ON A.CD_ESTADO = B.CD_ESTADO AND A.TIPO = B.TIPO
JOIN #SINCRONIZADOS_ESTADO_TIPO_AUDIO C ON B.CD_ESTADO = C.CD_ESTADO AND B.TIPO = C.TIPO
ORDER BY A.NM_ESTADO ASC