DROP TABLE IF EXISTS #BASE_CORRETORES
SELECT * 
INTO #BASE_CORRETORES
FROM pmcq..TEMP_ARTHUR_CORRETORES_185
WHERE NU_CPF IN (
					SELECT CD_USUARIO FROM pmcq..TEMP_ARTHUR_GERAL_077
					WHERE NU_SEQUENCIAL IN(
						SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
					)
)

/*AUDIOS ENVIADOS*/
DROP TABLE IF EXISTS #ENVIADOS_CORRETORES
SELECT B.NU_CPF, B.NM_USUARIO, COUNT(A.NU_REFERENCIA_OBJETO) AS QTDE_AUDIO_ENVIADO
INTO #ENVIADOS_CORRETORES
FROM pmcq..TEMP_ARTHUR_GERAL_077 A
LEFT JOIN #BASE_CORRETORES B
ON B.NU_CPF = A.CD_USUARIO
GROUP BY B.NU_CPF, B.NM_USUARIO

/*AUDIOS CORRIGIDOS*/
DROP TABLE IF EXISTS #CORRIGIDOS_CORRETORES
SELECT B.NU_CPF, B.NM_USUARIO, COUNT(A.NU_REFERENCIA_OBJETO) AS QTDE_AUDIO_CORRIGIDO
INTO #CORRIGIDOS_CORRETORES
FROM pmcq..TEMP_ARTHUR_GERAL_077 A
LEFT JOIN #BASE_CORRETORES B
ON B.NU_CPF = A.CD_USUARIO
WHERE A.TP_STATUS = '99'
GROUP BY B.NU_CPF, B.NM_USUARIO

/*QTDE AUDIO ENVIADO E CORRIGIDO JUNTOS*/
DROP TABLE IF EXISTS #JUNCAO_CORR_ENV
SELECT A.NU_CPF, 
       A.NM_USUARIO, 
       A.QTDE_AUDIO_ENVIADO, 
       COALESCE(B.QTDE_AUDIO_CORRIGIDO, 0) AS QTDE_AUDIO_CORRIGIDO
INTO #JUNCAO_CORR_ENV
FROM #ENVIADOS_CORRETORES A
LEFT JOIN #CORRIGIDOS_CORRETORES B ON A.NU_CPF = B.NU_CPF

/*JUNÇÃO COM NU_SEQUENCIAL PARA SABERMOS O ESTADO*/
DROP TABLE IF EXISTS #TESTE2
SELECT 
	   A.NU_CPF,
       A.NM_USUARIO,
       A.QTDE_AUDIO_ENVIADO,
       A.QTDE_AUDIO_CORRIGIDO,
       MAX(B.NU_SEQUENCIAL) AS NU_SEQ_MAX
INTO #TESTE2
FROM #JUNCAO_CORR_ENV A 
LEFT JOIN pmcq..TEMP_ARTHUR_GERAL_077 B ON A.NU_CPF = B.CD_USUARIO
GROUP BY A.NU_CPF, A.NM_USUARIO, A.QTDE_AUDIO_ENVIADO, A.QTDE_AUDIO_CORRIGIDO

DROP TABLE IF EXISTS #RESULTADO_FINAL_CORRETORES
SELECT 
		A.NU_CPF, 
		A.NM_USUARIO, 
		[TIPO] = 'CORRETOR',
		B.NM_ESTADO, 
		A.QTDE_AUDIO_ENVIADO, 
		A.QTDE_AUDIO_CORRIGIDO 
INTO #RESULTADO_FINAL_CORRETORES
FROM #TESTE2 A 
LEFT JOIN [T6_MEXICO_FLUENCIA_2024].[dbo].[1612_1896_MEXICO_CORRETORES] B
ON A.NU_CPF = B.NU_CPF
WHERE B.NM_ESTADO IS NOT NULL
union
SELECT 
		A.NU_CPF, 
		A.NM_USUARIO, 
		[TIPO] = 'SUPERVISOR',
		[NM_ESTADO] = 'GENERAL', 
		A.QTDE_AUDIO_ENVIADO, 
		A.QTDE_AUDIO_CORRIGIDO 
FROM #TESTE2 A 
LEFT JOIN [T6_MEXICO_FLUENCIA_2024].[dbo].[1612_1896_MEXICO_SUPERVISORES] B
ON A.NU_CPF = B.NU_CPF
WHERE A.NU_CPF not in (SELECT NU_CPF FROM [T6_MEXICO_FLUENCIA_2024].[dbo].[1612_1896_MEXICO_CORRETORES])
ORDER BY A.NU_CPF


/*---------- RELATORIO ----------*/

SELECT * FROM #RESULTADO_FINAL_CORRETORES

/*----------------------------------------------*/
--SELECT * FROM pmcq..TEMP_ARTHUR_GERAL_077
--SELECT * FROM PMCQ..TEMP_ARTHUR_GERAL_005
/*

/*JUNÇÃO DO 008 COM O 077*/
SELECT * FROM pmcq..TEMP_ARTHUR_GERAL_077 A
inner JOIN
(
	SELECT NU_SEQUENCIAL, CD_REGISTRO_CAED
	, SUBSTRING(SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,100),1,CHARINDEX('-',SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,100))-1) AS CD_ITEM 
	, SUBSTRING(SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,20),CHARINDEX('-',SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,20))+1,20) AS NU_CORRECAO
	, VL_CAMPO_200 
	FROM PMCQ..TEMP_ARTHUR_GERAL_008 
	WHERE CD_REGISTRO_CAED LIKE '%-%'
	AND (CD_REGISTRO_CAED LIKE '%-0' OR VL_CAMPO_200 IS NOT NULL) --> VL_CAMPO_200 não pode ser nulo caso não seja correção de IA
	AND NU_SEQUENCIAL IN(
	SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
)
)B 
ON A.NU_SEQUENCIAL = B.NU_SEQUENCIAL
AND A.CD_ITEM = B.CD_ITEM
AND A.NU_CORRECAO = B.NU_CORRECAO






SELECT NU_SEQUENCIAL, CD_REGISTRO_CAED
	, SUBSTRING(SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,100),1,CHARINDEX('-',SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,100))-1) AS CD_ITEM 
	, SUBSTRING(SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,20),CHARINDEX('-',SUBSTRING(CD_REGISTRO_CAED,CHARINDEX('-',CD_REGISTRO_CAED)+1,20))+1,20) AS NU_CORRECAO
	, VL_CAMPO_200 
	FROM PMCQ..TEMP_ARTHUR_GERAL_008 
	WHERE CD_REGISTRO_CAED LIKE '%-%'
	AND NU_SEQUENCIAL IN(
		SELECT NU_SEQUENCIAL FROM PMCQ..TEMP_ARTHUR_GERAL_005   
	)
	AND NU_SEQUENCIAL IN (
		SELECT NU_SEQUENCIAL FROM pmcq..TEMP_ARTHUR_GERAL_077 WHERE TP_STATUS = '99'
	)
	AND CD_ITEM IN (
		SELECT CD_ITEM FROM pmcq..TEMP_ARTHUR_GERAL_077 WHERE TP_STATUS = '99'
	)

*/